# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AFR Experience Guide
subtitle: The Australian Financial Review
email:
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
brandurl: ""
url: "" # the base hostname & protocol for your site
collections:
    typography:
        output: true
    colours:
        output: true

# Build settings
markdown: kramdown
